Fix invalid xml when pivot table created with more than one column in data field
caxlsx/caxlsx pull request #123
Opened 2022-01-13 16:07 UTC by westonganger

Solves #110

2022-01-13 16:07 UTC, westonganger commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
Should this also check columns.size?

2022-01-20 19:13 UTC, straydogstudio commented
@simi @noniq Do you see any reason we shouldn't merge this? I don't. It has tests now, and it passes.

2022-01-20 19:23 UTC, straydogstudio commented
@kiskoza You too. Any comments

2022-01-20 19:50 UTC, simi approved these changes

2022-01-21 08:44 UTC, kiskoza requested changes

2022-01-21 08:44 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
I would keep the style of the original code unless it has some real performance improvement. It might require to split this line into more to include the conditional part, but the it's much easier to read the gem's code when it has the same code-style everywhere (should change it back to `string << "something" << variable << "other sthing"` stlye)

2022-01-24 21:59 UTC, westonganger commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
Just throwing this out there...

Does anyone actually like the old formatting? If not then I believe we should be actively seeking to improve the codebase not just holding onto legacy ideals without gainful purpose.

I find the old formatting cryptic and hard to work with. A change like this makes the code just a little easier to work with. I think thats a good reason to allow it.

Any other contributors have comments here?

2022-01-25 08:29 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
I know you said other contributors, but here I am again :D I personally don't like the current code style and I experimented with it a few times, tried to introduce frozen string literarls, etc, but I either I wasn't happier with the new format or it got worse in perfomance. I think we should open a new issue discussing code styles and how to improve them as this project woul benefit a lot from rubocop or any other static analyzer that makes the code consistent and more performant

2022-01-25 08:32 UTC, noniq commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
If I remember correctly this style dates back to to commits like 22a341841f191a5. Originally Nokogiri was used to generate the XML, in these commits it got replaced by simple string concatenation to improve performance and reduce memory load. 

This distinct style of string concatenation was chosen because it was thought to be most memory-efficient. Not sure though if this was based on real tests or rather on gut feelings. 

And even if it was the most efficient way back then: Ruby's memory handling has changed a lot in the last 10 years, so this might no longer be true anyway.

2022-01-27 16:49 UTC, noniq commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
I agree with @kiskoza: Let’s keep the current coding style for now (as cryptic as it unfortunately is), and move the discussion about it into a separate issue or PR.

2022-01-27 20:00 UTC, straydogstudio commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +      str << %Q(<pivotTableDefinition xmlns="#{XML_NS}" name="#{name}" cacheId="#{cache_definition.cache_id.to_s}" #{'dataOnRows="1"' if data.size <= 1} applyNumberFormats="0" applyBorderFormats="0"
Sounds good to me. Are we ready to merge?

2022-01-28 19:31 UTC, merged

2022-01-28 21:22 UTC, straydogstudio commented
@westonganger Nice work. Thanks everyone.