Merge axlsx_styler gem into caxlsx
caxlsx/caxlsx pull request #168
Opened 2022-09-30 03:57 UTC by westonganger

### Description
Merge axlsx_styler gem into caxlsx. As bought up in #167.

- This is a first pass on this. We can iterate on it.
- A few `TODO` to be addressed

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

### After this is merged

We need to make some changes to `axlsx_styler` some short time after a successful release version release of caxlsx

1. Add a notice on the top of the axlsx_styler readme
2. Cut a new release which raises an exception if a newer non-supported caxlsx version is used (since the older versions dont restrict caxlsx version heavily).

2022-09-30 15:16 UTC, straydogstudio commented
Thanks for the quick work @westonganger

2022-10-09 20:51 UTC, westonganger commented on lib/axlsx.rb
> +  def self.hash_deep_merge(first_hash, second_hash)
Modeled after https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/hash/deep_merge.rb

2022-10-11 11:22 UTC, kiskoza requested changes
Thanks for the PR, I left a few comments we need to fix. I saw a few TODOs in the comments, can we address them? (e.g: remove them if they are not relevant). Also there is a test/tc_axlsx file which is empy, maybe by an accident?

2022-10-11 11:22 UTC, kiskoza commented on lib/axlsx/workbook/workbook.rb
> +    # Checks if styles are indexed to make it work for pre 0.1.5 version
I don't think we still need this check, we should not bring over legacy codes

2022-10-11 11:22 UTC, kiskoza commented on examples/add_border_example.md
> +![Output](images/add_border.png "Output")
the screenshot seems to be missing, also we should name it the same as the .md file (e.g.: add_broder_example.png)

2022-10-13 06:24 UTC, westonganger commented on lib/axlsx/workbook/workbook.rb
> +    # Checks if styles are indexed to make it work for pre 0.1.5 version
Ok I updated the comment. However this is actually a useful method/attr

2022-10-13 06:25 UTC, westonganger commented on examples/add_border_example.md
> +![Output](images/add_border.png "Output")
Added the screenshots

2022-10-13 06:27 UTC, westonganger commented
@kiskoza ok I have resolved all the TODO's and addressed your comments.

2022-10-21 00:04 UTC, westonganger commented
Seems to me this is more or less ready to go. Any more comments here.

2022-10-21 06:39 UTC, kiskoza approved these changes
Sorry for the delay, it was a busy week for me. Thanks for solving all my comments, it looks good to me, ready to merge :+1:

2022-10-21 11:19 UTC, merged

2022-10-21 11:22 UTC, straydogstudio commented
Do we want to release a 3.2.1 version?

2022-10-21 17:28 UTC, westonganger commented
I have now released v1.2.0 of axlsx_styler which drops support for 3.3.0+ and added a notice at the top of the axlsx_styler readme