feat: add support for remote images
caxlsx/caxlsx pull request #177
Opened 2022-12-27 17:14 UTC by sebastianobar

### Description
Add support for remote images insert

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

2023-02-01 14:35 UTC, kiskoza requested changes
Thanks for your contribution, the code looks well prepared. I added a few comments, ping me here or on Slack if you have any questions about them.

2023-02-01 14:35 UTC, kiskoza commented on lib/axlsx/drawing/pic.rb
> +    def remote?
I usually like helper methods with a `?`, however it does not really add any extra meaning here. If you check the codebase, all of the `?` helpers are a bit more complex and the boolean attributes are just used as-is.

2023-02-01 14:35 UTC, kiskoza commented on test/drawing/tc_pic.rb
> +    assert_equal(@p.workbook.images[1], @image_remote)
this line ended up a bit confusing to read as the previous test is using `images.first` and this one is `images[1]`, at first glance it's easy to misread what's going on. as we're not using ActiveSupport to have `second`, etc, it would be nice to chage the other test to match the same pattern and use `images[0]` there.

2023-02-01 14:35 UTC, kiskoza commented on test/util/tc_mime_type_utils.rb
> +    assert_equal(Axlsx::MimeTypeUtils::get_mime_type_from_uri(@test_img_url), 'image/png')
some of the tests are failing without an active internet connection, which is expected as we're loading the mimetype on the fly, but I'm not sure if this is the good way. on the other hand, setting up webmocks and / or local server sounds too much for this feature, so personally I would leave it for now

2023-02-01 14:35 UTC, kiskoza commented on CHANGELOG.md
> +  - Add support for remote image source in `Pic` using External Relationship (supported in Excel documents)
could you extend our `examples/image_example.md` with and example loading a remote image? it would help others find this feature and easier to verify that the file looks okay in the end

2023-02-01 14:35 UTC, kiskoza commented on lib/axlsx/drawing/pic.rb
> +    def remote=(v) @remote = v; end
could you add a `Axlsx::validate_boolean v` to this method to ensure that it's a boolean?

2023-02-19 13:12 UTC, sebastianobar commented on test/util/tc_mime_type_utils.rb
> +    assert_equal(Axlsx::MimeTypeUtils::get_mime_type_from_uri(@test_img_url), 'image/png')
actually i have the same problem on the main test for this feature ( `test/drawing/tc_pic` ), because when I test the Pic in "remote mode" it will try to check the MimeType from uri on the process behind. How do you suggest to approach this tests? I'll have to remove all tests that requires a connection or add webmock configuration?

2023-02-20 08:37 UTC, kiskoza commented on test/util/tc_mime_type_utils.rb
> +    assert_equal(Axlsx::MimeTypeUtils::get_mime_type_from_uri(@test_img_url), 'image/png')
@simi @noniq @straydogstudio what do you think about this one?

2023-02-20 23:33 UTC, straydogstudio commented on test/util/tc_mime_type_utils.rb
> +    assert_equal(Axlsx::MimeTypeUtils::get_mime_type_from_uri(@test_img_url), 'image/png')
Doing a local server does seem too much. For testing, I don't think it is unreasonable to expect an internet connection. The worst that will happen is that test fails, and it shouldn't happen on any automated test system that we use. I suggest making a separate routine for remote mime testing so the regular one doesn't fail without network. And make sure the failure message is clear. 

Is it possible to make test-unit tests optional?

2023-04-12 15:37 UTC, kiskoza commented
I've rebased and merged this PR: https://github.com/caxlsx/caxlsx/commit/2d714298a462a1482bd8e12fbb2efb74d6acee5f

2023-04-12 15:37 UTC, closed without merging

2023-04-12 17:10 UTC, tagliala commented on lib/axlsx/drawing/pic.rb
> +      end
Isn't this `remote == 1 || remote.to_s == 'true'` ?

2023-04-12 17:34 UTC, kiskoza commented on lib/axlsx/drawing/pic.rb
> +      end
yes, it the same ;) Fixed in https://github.com/caxlsx/caxlsx/commit/518e74f8769daf67fca461139d3c7229abdb6e60 to pass rubocop before I merged this PR