escape_formulas - add settings for global, workbook, worksheet, row and cell levels
caxlsx/caxlsx pull request #186
Opened 2023-03-30 19:42 UTC by johnnyshields

This PR does the following:
- Fixes #174 *without* setting default to true
- Fixes #190

This PR should be merged and released as version `3.4.0`. It is a precursor to https://github.com/caxlsx/caxlsx/pull/189 which should be released as `4.0.0`.

2023-03-30 19:43 UTC, johnnyshields commented on lib/axlsx.rb
> +    @escape_formulas || false
For version 4.0, all we need to do is switch the default value to `true` here (global setting)

2023-03-30 20:50 UTC, tagliala requested changes

2023-03-30 20:50 UTC, tagliala commented on lib/axlsx/workbook/workbook.rb
>    end
Is it possible to backport all the style changes, typo fixes, and the fix to `module` position to master?

2023-03-31 03:11 UTC, johnnyshields commented on lib/axlsx/workbook/workbook.rb
>    end
Done, see: https://github.com/caxlsx/caxlsx/pull/188

2023-04-01 10:25 UTC, tagliala commented on test/workbook/tc_workbook.rb
> +    Axlsx.instance_variable_set(:@escape_formulas, nil)
should this be done in an `ensure` block?

2023-04-01 18:44 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !@value.start_with?(*FORMULA_PREFIXES) # Not a formula
I think this is a different security issue and should be addressed in a different PR and released like right now in 3.x :) 

I think this deserves a CVE

2023-04-02 05:56 UTC, johnnyshields commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !@value.start_with?(*FORMULA_PREFIXES) # Not a formula
@tagliala good point, I've raised https://github.com/caxlsx/caxlsx/issues/190 and filed a separate CVE.

2023-04-03 09:03 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
> +
Yeah, I was thinking that this check was missing too

2023-04-03 09:05 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
>        type == :string && @value.to_s.start_with?('{=') && @value.to_s.end_with?('}')
```suggestion
      type == :string && @value.to_s.start_with?('{=') && @value.to_s.end_with?('}')
```

I'm not confident about this check, but again, I'm no expert of how excel works

I may logically think that this should also check for `{@`, `{+`, etc. but actually I wasn't able to replicate an issue with a formual starting with `@` or `+`.

I was thinking to something like ARRAY_FORMULA_PREFIXES which takes FORMULA_PREFIXES and maps it with a leading `{`. If you have a reproducible test case with a formula starting with any other character than `=` it could help me

2023-04-03 11:16 UTC, johnnyshields commented on lib/axlsx/workbook/worksheet/cell.rb
>        type == :string && @value.to_s.start_with?('{=') && @value.to_s.end_with?('}')
We should verify that `{@`, `{|` etc. are actually an issue...

2023-04-03 11:23 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
>        type == :string && @value.to_s.start_with?('{=') && @value.to_s.end_with?('}')
I can't even replicate issues with formulas starting with `+` on my excel version

2023-04-11 13:25 UTC, tagliala commented
Hi,

after I've spent some time into the source code, I think that:
- Array formula escaping should be fixed and merged separately because it is an existing issue not related to this problem and a version bump is not required. A potential breaking change should be considered a security fix (ref: #192)
- The majority of files is requiring on top, but `lib/axlsx/workbook/workbook.rb` is not the only file calling `require` inside the module. We should highlight all those files and address this issue separately. This will reduce the number of changes in this PR
- `FORMULA_PREFIXES` could be moved to `lib/axlsx/util/constants.rb` like all other constants

Still missing:
- An `ARRAY_FORMULA_PREFIXES` may be needed
- Understand if `{+formulas}` may be a security issue. In the doubt, I suggest to escape them

2023-04-12 15:08 UTC, johnnyshields commented on test/workbook/worksheet/tc_cell.rb
> +      sheet.add_row ["=1+1", "-1+1"], types: :text
Yes, its wrong on master and the spec "just happens" to work.

2023-04-12 15:40 UTC, johnnyshields commented
@tagliala In addition to fixing the non-array cases, this PR fixes formula injection for the `{=` case. Whatever you'd like to fix in addition, please do it in a follow-up PR as this one is ready to merge today.

@kiskoza please review this and if you're good to merge please do so.

2023-04-12 15:41 UTC, johnnyshields commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !is_array_formula?        # Not an array formula
This line fixes array injection for `{=`

2023-04-12 15:53 UTC, merged

2023-04-12 15:56 UTC, kiskoza commented
@johnnyshields @tagliala thanks for all the work :rocket:

I accidentally broke the CI for ruby 2.3 and 2.4 with an other PR, I'm going to fix that and prepare a new 3.4.0 release

2023-04-12 17:35 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !is_array_formula?        # Not an array formula
> This line fixes array injection for `{=`

As far as I understand, this is actually incorrect

The code here is only used when the option `p.use_shared_strings = true` is enabled (which is `false` by default).

The fix is done in the `is_array_formula?` guard clause returning `false` when escape formula option is enabled