Escape formulas by default
caxlsx/caxlsx pull request #189
Opened 2023-04-01 01:04 UTC by johnnyshields

This is a follow-up to https://github.com/caxlsx/caxlsx/pull/186. It should be released as version 4.0.

2023-04-02 07:26 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
>      def is_array_formula?
I do not know how excel works, but I can see that this method is also checking for an `=`.

```rb
    def is_array_formula?
      type == :string && @value.to_s.start_with?('{=') && @value.to_s.end_with?('}')
    end
```

Should this be fixed too?

2023-04-02 08:41 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
>      def is_array_formula?
I think it should. it is possible to get a security warning on macOS with the following template:

```rb
# frozen_string_literal: true

rows = [
  "{=cmd|'/C calc'!A0}"
].freeze

wb = xlsx_package.workbook

wb.add_worksheet(name: 'Test') do |sheet|
  sheet.add_row(rows, escape_formulas: true)
end
```

<img width="372" alt="image" src="https://user-images.githubusercontent.com/556268/229342114-623835bb-600a-4760-9be1-09ced465df4b.png">

2023-04-02 16:55 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !@value.start_with?(*FORMULA_PREFIXES) # Not a formula
I did not understand exactly what Shared Strings are, but:

1. Should this also check for an array formula?
2. Should this use `!is_formula?` itself

```suggestion
        !is_formula? &&           # Not a formula
        !is_array_formula?        # Not an array formula
```

2023-04-03 01:02 UTC, johnnyshields commented on lib/axlsx/workbook/worksheet/cell.rb
>      def is_array_formula?
@tagliala Just committed a fix, please check it now.

2023-04-03 01:02 UTC, johnnyshields commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !@value.start_with?(*FORMULA_PREFIXES) # Not a formula
Done.

2023-04-05 07:15 UTC, tagliala commented on lib/axlsx/workbook/worksheet/cell.rb
>      def is_array_formula?
With the fix it works.

But I'm still unable to replicate issues on excel with formulas starting with `+`, so I still can't tell if `{+` is actually an issue. I've read that "DDE server" must be enabled, but I also tried that and it does not work.

I would say to escape the chars in case of doubt

2023-04-12 16:34 UTC, johnnyshields commented on lib/axlsx/workbook/worksheet/cell.rb
> +        !is_array_formula?        # Not an array formula
OK, do it in a later PR

2023-04-12 17:47 UTC, johnnyshields commented
@kiskoza I'll try to rebase this tomorrow. I'm thinking to also add "use_formulas" as an inverse alias of "escape_formulas" since its much more natural to be "opting-in"

2023-04-12 18:09 UTC, johnnyshields commented
@kiskoza this is ready to merge. I'm not sure why Ruby 2.3 and 2.4 are failing, it doesn't look related to this PR.

We should probably drop support for those anyway as they are deep-EOL.

2023-04-12 18:12 UTC, kiskoza commented
thanks @johnnyshields . Let's try to merge in #202 first and release the gem and then we can pick up your PR and make sure everything is working for 4.0 - we're almost there :D

2023-04-13 12:15 UTC, kiskoza commented
@johnnyshields can you do one more rebase onto master? (last one, I promise :smile: ) you also mentioned a `use_formulas` inverse alias, should I wait for it before reviewing the PR?

2023-04-26 07:23 UTC, kiskoza requested changes
We need to adjust our examples folder as well - there are some examples using formulas without the explicit escape_formulas flag

2023-07-26 07:16 UTC, tagliala commented
Keep open

2023-10-19 08:14 UTC, kiskoza commented
I've merged in my rebased version without conflicts, see #307

2023-10-19 08:14 UTC, closed without merging