Added sorting to the AutoFilter class - add sort conditions to the xml
caxlsx/caxlsx pull request #286
Opened 2023-06-15 12:52 UTC by rikweelvoormedia

### Description
Added two new classes, `SortState` and `SortCondition` to the `AutoFilter` class to make sorting on export possible.

They follow roughly the same logic as the `AutoFilter` class itself. The two classes are nested in `AutoFilter` because also where they are represented in the xml. The sorting (just like the filters) is directly applied to the rows of the worksheet. I added an option to `AutoFilter` `(set_sort_on_generate)` to not do that which might have a preference when working with large datasets. Because the conditions are represented in the XML, they will still be visible in the sort options of the file. Sorting rules are added using `the sort_state.add_sort_condition` method which takes 3 arguments; the respective column id (the only required argument), an order direction `(:asc or :desc)` which is set to ascending by default and an array representing a custom order list. Multiple conditions are added in order of priority, where the first added takes the highest priority. 
Xml wise the sortState is child component of the autoFilter class, so an `AutoFilter` should be initialised if a `SortState` needs to be added to the file

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [x] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

2023-06-15 16:41 UTC, tagliala commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
can you please run `rubocop` locally? These lines should trigger an offense

2023-06-16 09:15 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
HI Geremia, quick reply, thanks! I just pushed the commits with the fixed Rubocop offenses.

2023-06-21 14:54 UTC, kiskoza commented
hi, thanks for your contribution, its always nice to see some improvements for the gem. Could you add an example code and screenshot to make sure we're on the same page of what should be implemented here, how to use it, etc?

2023-06-22 09:42 UTC, rikweelvoormedia commented
> 

Hi Zsolt, thanks! I just added some examples to the directory but please reach out if anything remains unclear.

2023-06-22 09:55 UTC, rikweelvoormedia commented
> From code coverage, I can see that specs do not cover
> 
> * `if cell_value_row1.nil? || cell_value_row2.nil?`
> * `elsif condition.custom_list.empty?`
> * `def sort_on_generate=(v)`

Geremia could you elaborate a bit more on what you mean by this? In the meantime I fixed the sorting if a cell value is nil, but what is your question on `elsif condition.custom_list.empty?` and `def sort_on_generate=(v)` exactly?

2023-06-22 10:01 UTC, tagliala commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
> +      if !sort_state.sort_conditions.to_a.empty? && self.sort_on_generate
```suggestion
      if !sort_state.sort_conditions.to_a.empty? && sort_on_generate
```

`self.` will trigger an offense after #285

2023-06-22 11:24 UTC, kiskoza requested changes
thanks for the example, it was a bit easier to review the code with a working example. I've found a few lines that should be improved, but it feels very promising

2023-06-22 11:24 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/auto_filter/sort_condition.rb
> +    def get_column_letter(col_id)
this seems to be re-iplementing Axlsx.col_ref from `lib/axlsx.rb#110`

2023-06-22 11:24 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/auto_filter/sort_state.rb
> +    def add_sort_condition(col_id, order: :asc, custom_list: [])
it feels weird to me that we need to pass in column indexes instead of the column letters. the index would make sense if we would handle them as an offset from the start of the auto-filter area

2023-06-22 11:24 UTC, kiskoza commented on test/workbook/worksheet/auto_filter/tc_auto_filter.rb
>  class TestAutoFilter < Test::Unit::TestCase
we should keep the original tests as they are now to make sure that we don't lose a functionality and add a new test case handling the new sort state feature

2023-06-22 14:28 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
> +      if !sort_state.sort_conditions.to_a.empty? && self.sort_on_generate
removed .to_a from line 62 and 63

2023-06-22 15:14 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/sort_state.rb
> +    def add_sort_condition(col_id, order: :asc, custom_list: [])
I agree, this is not intuitive now. If we keep in line with the auto filter, the index from the offset would make most sense to me.

2023-06-23 14:58 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/sort_condition.rb
> +    def get_column_letter(col_id)
Using that function now.

2023-06-23 15:02 UTC, rikweelvoormedia commented on test/workbook/worksheet/auto_filter/tc_auto_filter.rb
>  class TestAutoFilter < Test::Unit::TestCase
restored it.

2023-06-23 15:04 UTC, rikweelvoormedia commented
I implemented the requested changes into the PR. Happy to go through the code again if anything remains unclear!

2023-06-27 07:33 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/auto_filter/sort_state.rb
> +    def add_sort_condition(col_id, order: :asc, custom_list: [])
can we call it column_offset or something similar to indicate the true meaning? also it would be nice to have it as a named parameter as the others

```ruby
def add_sort_condition(column_offset:, order: :asc, custom_list: [])
  ...
end
```

2023-07-06 10:25 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/sort_state.rb
> +    def add_sort_condition(col_id, order: :asc, custom_list: [])
I agree that it can be more clear, but I don't know if column_offset really justifies the meaning of the parameter. I changed it to column_index. I also added a validator to check if the argument is an integer and it is a named parameter now.

2023-07-07 13:23 UTC, rikweelvoormedia commented
I updated the tests and example. It should be in a reviewable state now in it's completeness, please let me know if more can be improved!

2023-07-07 19:13 UTC, tagliala commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
> +    end
is it possible that this will return false?

2023-07-07 19:15 UTC, tagliala commented on lib/axlsx/workbook/worksheet/auto_filter/sort_condition.rb
> +    end
since instance variables are used in read only in this context, is it possible to use the attribute reader version? (`order` instead of `@order`)

2023-07-10 08:45 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
> +    end
Good catch, I refactored it a bit. `sort_on_generate ` initialises set to true. I also added an attribute reader.

2023-07-10 08:45 UTC, rikweelvoormedia commented on lib/axlsx/workbook/worksheet/auto_filter/sort_condition.rb
> +    end
done!

2023-07-10 08:46 UTC, rikweelvoormedia commented
refactored some minor details and fixed some unexpected behaviour regarding sorting on a custom list.

2023-07-12 11:20 UTC, kiskoza requested changes

2023-07-12 11:20 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/auto_filter/auto_filter.rb
> +            comparison = if cell_value_row1.nil? || cell_value_row2.nil?
Sorry for picking this one again, but it still feels incomplete for me

```ruby
comparison = if cell_value_row1.nil? && cell_value_row2.nil?
               # If both of them are nil, then they are equal
               0
             elsif cell_value_row1.nil?
               # Following the original logic, not sure if nils should be at the beginning or the end of the list
               -1
             elsif cell_value_row2.nil?
               1
             elsif custom_list.empty?
               cell_value_row1 <=> cell_value_row2
             else
               # Calculate the indexes only once
               index1 = custom_list.index(cell_value_row1)
               index2 = custom_list.index(cell_value_row2)

               if index1.nil? && index2.nil?
                 # We can sort them by their original value or go with 0 to be sorted on the next sort condition
                 cell_value_row1 <=> cell_value_row2
               elsif index1.nil?
                 # Following the original logic, seems to inconsistent with the nil value sorting
                 1
               elsif index2.nil?
                 -1
               else
                 index1 <=> index2
               end
             end
```

2023-08-02 09:07 UTC, rikweelvoormedia commented
Hi guys, please let me know if anything remains unclear. What are the issues blocking this PR from being merged into the library now?

2023-08-02 09:50 UTC, kiskoza commented
Hi. Sorry for the delay, I'm trying to find some time to do a final review / testing for this PR - I hope I can do it in soonish

2023-08-11 08:10 UTC, kiskoza approved these changes
Thanks, it looks great now! Sorry for postponing the review for so long

2023-08-14 17:03 UTC, rikweelvoormedia commented
Great, please merge when you guys feel ready!

2023-08-15 07:30 UTC, merged