No grand totals option for Pivot Table
caxlsx/caxlsx pull request #359
Opened 2024-03-09 10:52 UTC by vknightbd

### Description
Add `PivotTable#no_grand_totals` option to remove grand totals row/col

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

2024-03-11 18:41 UTC, vknightbd commented
I'm not sure what documentation is required. I looked at an existing PivotTable option `no_subtotals_on_headers` and it seems like no documentation exists. Maybe we need to start a document that simply lists the PivotTable options?

2024-03-22 10:51 UTC, kiskoza requested changes
Hi. Thanks for your contribution, we highly appreciate it. The code works fine, but I got some questions reading the changes, let's discuss them.

The documentation you added are enough for me, if you have some time, you can expand out examples folder to make this feature more discoverable

2024-03-22 10:51 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +    attr_accessor :no_grand_totals
You should add a `@return [Symbol]` comment to indicate that this accessor hold a symbol.

I would add a default value (maybe `:none`) in the initializer. Defining the instance variables in the same order helps the runtime, and in my opinion it's better to have a default value than handling `nil`s.

Then, I would change this into an `attr_reader` and define a writer method (`no_grand_totals=`) with a validator, something like `RestrictionValidator.validate "PivotTable.no_grand_totals", [:row, :col, :both, :none], v`. You can find examples in the codebase.

And lastly - it's a bit confusing to me to define which ones I don't need, what do you think turning it to the opposite? `grand_totals` would default to `both` and the other options would be `only_row`, `only_col` and `none`.

2024-03-22 10:51 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +          str << "<dataField name='#{datum_value[:subtotal]&.capitalize || ''} of #{datum_value[:ref]}' fld='#{header_index_of(datum_value[:ref])}' baseField='0' baseItem='0'"
I'm not sure why do we need this capitalize call, could you give me some details?

2024-03-22 10:51 UTC, kiskoza commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +    # Hash in format of { ref: header, num_fmt: numFmts, subtotal: subtotal }, where header is String, numFmts is Integer, and subtotal one of %w[count average max min product countNums stdDev stdDev
Nice description :)

2024-03-22 16:56 UTC, vknightbd commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +    attr_accessor :no_grand_totals
`grand_totals` is definitely more intuitive! (I think I was trying to be unobtrusive to the existing functionality, similar to the existing `no_subtotals_on_headers`)

2024-03-22 18:44 UTC, vknightbd commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +    # Hash in format of { ref: header, num_fmt: numFmts, subtotal: subtotal }, where header is String, numFmts is Integer, and subtotal one of %w[count average max min product countNums stdDev stdDev
I've updated the description. When subtotal is left blank, Excel interprets it as "sum"

2024-03-22 18:48 UTC, vknightbd commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +          str << "<dataField name='#{datum_value[:subtotal]&.capitalize || ''} of #{datum_value[:ref]}' fld='#{header_index_of(datum_value[:ref])}' baseField='0' baseItem='0'"
`datatum_value[:subtotal]` is lowercase as it is assigned in the following xml attribute. For example, `subtotal=average`. But the field label should be capitalized, for example, if the field is "sales', it should be "Average of Sales". (These are assumptions I'm making based on what I've seen in creating a pivot table in Excel.)

2024-03-22 18:54 UTC, vknightbd commented on lib/axlsx/workbook/worksheet/pivot_table.rb
> +          str << "<dataField name='#{datum_value[:subtotal]&.capitalize || ''} of #{datum_value[:ref]}' fld='#{header_index_of(datum_value[:ref])}' baseField='0' baseItem='0'"
I see that this `capitalize` is really just a bandaid fix. By default, subtotal is unspecified, so you get a weird " of Sales" as the label. I've gone ahead and implemented a proper fix so that it should show "Sum of Sales". I've removed the comment `# The correct name prefix in ["Sum","Average", etc...]` as it should be more self-explanatory now. I've also fixed the screenshot.

2024-04-11 07:57 UTC, kiskoza approved these changes

2024-04-11 08:01 UTC, merged