Fix worksheet title length enforcement
caxlsx/caxlsx pull request #70
Opened 2020-11-26 18:56 UTC by klyonrad

2020-12-03 22:27 UTC, noniq requested changes

2020-12-03 22:27 UTC, noniq commented on test/workbook/worksheet/tc_worksheet.rb
> -  def test_exception_if_name_too_long
I suppose you removed this test because `test_name_size` (line 470ff) is more or less the same? That’s a good idea, but I think it would be even better to keep *this* test and delete the other one (it uses `Array.new(31, "A").join()` to construct the string, which I find a bit contrieved). 

In addition, if we keep this test, `test_exception_if_name_too_long_because_of_multibyte_characters` should also stay here instead of being moved to the end of the file.

2020-12-03 22:27 UTC, noniq commented on test/workbook/worksheet/tc_worksheet.rb
> +      @ws.name = "#{four_characters_for_excel}1234567890123456789012345678"
Might be a bit easier to grasp if written like this:

```suggestion
      @ws.name = four_characters_for_excel + "x" * 28
```

2020-12-03 22:27 UTC, noniq commented on CHANGELOG.md
> +  - [I #67](https://github.com/caxlsx/caxlsx/issues/67) - Fix worksheet name length enforcement. Some unicode characters were counted longer than necessary.
```suggestion
  - [I #67](https://github.com/caxlsx/caxlsx/issues/67) - Fix regression in worksheet name length enforcement: Some unicode characters were counted incorrectly, so that names that previously worked fine now stopped working. (This was introduced in 3.0.2)
```

2020-12-03 22:27 UTC, noniq commented on lib/axlsx/workbook/worksheet/worksheet.rb
> +      character_length = name.encode("utf-16").bytesize / 2 - 1
Maybe we can skip the division and simply use `… < 32`?

2020-12-09 14:43 UTC, klyonrad commented on test/workbook/worksheet/tc_worksheet.rb
> -  def test_exception_if_name_too_long
Yes, removed it because it is duplicate and it looked to me like the test was written there with oversight of  `test_name_size`

I had a similar thought upon removal but my approach was basically to not change more of the "historic" code than is required. Since they are probably still a lot of old PRs and forks to be pulled I would argue that not changing too much has still its benefits

---

Regarding the positioning: It seems I only looked down and not up. Grouping all the name tests together at the top makes sense

2020-12-09 14:43 UTC, klyonrad commented on lib/axlsx/workbook/worksheet/worksheet.rb
> +      character_length = name.encode("utf-16").bytesize / 2 - 1
Tried it out. That would make the tests green, but then the code would look like this

```ruby
      character_length = name.encode("utf-16").bytesize / 2
      raise ArgumentError, (ERR_SHEET_NAME_TOO_LONG % name) if character_length > 32
```

the code walk talk as if 32 is the character limit which it is not :/

2020-12-09 15:37 UTC, noniq commented on lib/axlsx/workbook/worksheet/worksheet.rb
> +      character_length = name.encode("utf-16").bytesize / 2 - 1
It seems that Ruby adds a BOM at the beginning of a string when encoding it as UTF-16:

```ruby
"123".encode("utf-16") # => "\uFEFF123"
```

The BOM counts for 2 bytes, but is probably irrelevant to Excel’s length restriction. If that’s the case, then something like this should work:

```ruby
utf16_name = name.encode("utf-16")[1..-1] # ignore first character (BOM) because Excel does so, too.
raise … if utf16_name.bytesize > 64 # or `>= 64`? I’m confused … 
```

2020-12-09 15:57 UTC, noniq commented on test/workbook/worksheet/tc_worksheet.rb
> -  def test_exception_if_name_too_long
Sorry I just now realized that you did create separate commits for reordering the tests and deleting the duplicate (b2c9fbca, f25ef021). Thats great! 🥳 

Let's keep b2c9fbca, but change f25ef021 to remove the other one of the duplicate tests, and then create a third commit on top containing the actual fix, Changelog entry and so on (it's okay to rebase/squash and force-push).

2020-12-10 12:15 UTC, klyonrad commented on test/workbook/worksheet/tc_worksheet.rb
> -  def test_exception_if_name_too_long
Done

2021-01-06 02:12 UTC, straydogstudio commented
@noniq Are we happy with the changes on this pull request?

2021-01-06 04:05 UTC, straydogstudio commented
The expression could remove division and retain some clarity like this:

```
byte_length = name.encode("utf-16")[1..-1].encode("utf-16").bytesize - 2
raise ArgumentError, (ERR_SHEET_NAME_TOO_LONG % name) if byte_length > 31 * 2
```

But I don't really see any gains by improving these lines. Certainly performing division by 2 for each sheet name is not a significant performance hit. Since other things are waiting on this and tests are passing, I'm going to merge this request. We can revisit this syntax in another pull request.

2021-01-06 04:07 UTC, merged

2021-01-06 04:51 UTC, straydogstudio commented
Released in 3.0.4