Add support for format in pivot tables
caxlsx/caxlsx pull request #79
Opened 2021-02-12 18:40 UTC by stonefield

Support number format in pivot tables.

2021-03-04 21:08 UTC, stonefield commented
@kiskoza How about merging this in. Easy fix, low risk.

2021-03-05 08:45 UTC, kiskoza commented
hi @stonefield . I don't have a merge permission on this repo, I'm just helping people here and there. I'm not sure why was this PR set aside, but here's my opinion:

Your code change in the lib seems to be right. However I don't like the idea of removing a test to prove a new feature, so your test code change should be moved to a new test case instead of changing an existing one. Unfortunately I never used pivot tables, so it would help a lot if you attach some screenshots / code snippets about the new features (what it looked like before your code change, what it looks like with this PR, how to achieve the old look if somebody wants that).

If you have any further questions, I'm here to help or you can [join our Slack](https://join.slack.com/t/caxlsx/shared_invite/enQtOTI5OTM0MzI1Njk5LTBlMDQzNDk2YzkwODMxMmVkODMyYzJiZGU5NTQ3YTg5NTBlN2IwZTlmNTRjNzhiY2E0MDY2OTEyYmFlODI5NjA)

2021-03-05 09:20 UTC, stonefield commented
Thanks for the feedback @kiskoza 
I will extract the test and provide an example on the difference it makes next week.

2021-03-13 12:42 UTC, stonefield commented
@kiskoza I have separated the test. I have also made an example of what formatting means to a pivot table.
The enclosed spreadsheet shows both formatted and unformatted pivot tables, where you can see the difference. 
Who should I ask to make the merge?
[PivotTableExample.xlsx](https://github.com/caxlsx/caxlsx/files/6134774/PivotTableExample.xlsx)

2021-03-16 16:11 UTC, kiskoza commented
Thanks for the test changes and the example file, now I see what you tries to accomplish - all looks good to me.

@noniq could you check and merge?

2021-03-18 22:47 UTC, noniq requested changes
Looks great, almost ready for merging! Please address the minor issue regarding the test case.

2021-03-18 22:47 UTC, noniq commented on test/workbook/worksheet/tc_pivot_table.rb
> +  end
Please add an assertion to also make sure that the `num_fmt` code actually ends up in the XML (currently the test still passes even if line 219 in pivot_table.rb is removed).

2021-03-19 10:29 UTC, stonefield commented on test/workbook/worksheet/tc_pivot_table.rb
> +  end
I made an improvement to the test. I hope that represents the change you pointed out should be there.

2021-03-19 10:46 UTC, noniq approved these changes

2021-03-19 10:47 UTC, merged

2021-03-19 10:47 UTC, noniq commented
Perfect. Thanks for your contribution!